# The API version strings to display in the documentation
COMMON_VERSION = '2015-12-09'

VERSIONS = {
    '@@PNAPI_VERSION': '2013-07-01',
    '@@NETWORK_API_VERSION': '2015-05-01',
    '@@CONVERSION_API_VERSION': COMMON_VERSION,
    '@@TRANSACTION_API_VERSION': COMMON_VERSION,
    '@@CALL_OUTCOME_VERSION': '2015-08-17',
}
