# The API version strings to display in the documentation
COMMON_VERSION = '2015-09-30'

VERSIONS = {
    '@@PNAPI_VERSION': '2013-07-01',
    '@@NETWORK_API_VERSION': COMMON_VERSION,
    '@@CONVERSION_API_VERSION': COMMON_VERSION,
    '@@TRANSACTION_API_VERESION': '2015-09-30',
    '@@CALL_OUTCOME_VERSION': '2015-08-17',
}
